const GAME_STATES = Object.freeze({
  LOBBY: 'LOBBY',
  ROUND_INTRO: 'ROUND_INTRO',
  WAGER_COLLECTION: 'WAGER_COLLECTION',
  QUESTION: 'QUESTION',
  SCOREBOARD: 'SCOREBOARD',
  BREAK: 'BREAK',
  MINI_GAME: 'MINI_GAME',
  FINAL_WAGER: 'FINAL_WAGER',
  FINAL_RESULTS: 'FINAL_RESULTS',
});

module.exports = { GAME_STATES };
